# Generated by Django 4.0.2 on 2022-02-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='checked',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='checked',
            field=models.BooleanField(null=True),
        ),
    ]
