# Generated by Django 4.0.2 on 2022-02-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0002_entry_checked_truck_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='quantity_received',
            field=models.IntegerField(null=True),
        ),
    ]
