# Generated by Django 4.0.2 on 2022-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0003_entry_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
