# Generated by Django 4.0.2 on 2022-02-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0004_alter_entry_checked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['material'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='material',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='material_description',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='truck',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
