# Generated by Django 4.0.2 on 2022-02-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0006_alter_entry_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
