# Generated by Django 4.0.2 on 2022-02-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0007_alter_entry_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='checked',
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
