# Generated by Django 4.0.2 on 2022-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0008_remove_truck_checked_alter_entry_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
